# Generated by Django 5.2.6 on 2025-10-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(related_name='games', through='store.GameTag', to='store.tag'),
        ),
    ]
