# Generated by Django 5.2.6 on 2025-10-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_review'),
        ('store', '0006_game_tags'),
    ]

    operations = [
    ]
