# Generated by Django 5.2.6 on 2025-12-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_promotion_promotionusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ai_verdict',
            field=models.TextField(blank=True, help_text='AI-generated consensus summary', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='external_sources',
            field=models.JSONField(blank=True, default=list, help_text='Citation metadata: [{source_name, url, sentiment}]', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_exists_externally',
            field=models.BooleanField(default=True, help_text='Whether game exists in external sources'),
        ),
        migrations.AddField(
            model_name='game',
            name='global_sentiment_score',
            field=models.FloatField(blank=True, help_text='Web sentiment score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='last_external_sync',
            field=models.DateTimeField(blank=True, help_text='Last time external data was fetched', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='last_local_sync',
            field=models.DateTimeField(blank=True, help_text='Last time local reviews were analyzed', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='local_rating',
            field=models.FloatField(blank=True, help_text='Local buyer rating (0-5 stars converted to 0-100)', null=True),
        ),
    ]
